# mkdocs.yml

site_name: PALIA - Manual usuario agencia
site_description: Documentación de usuario para la gestión de agencia

# Configuración del tema Material
theme:
  name: material
  features: 
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.copy.copy
  language: es
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Cambiar a Modo oscuro
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Cambiar a Modo claro
      primary: teal
      accent: lime

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/ceieu/posts/?feedView=all

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# Personaliza según tus necesidades y agrega más páginas en tu proyecto.
copyright: CEI Europe
